# Set update schedule for GitHub Actions
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
      time: "12:00"
    # Raise all npm pull requests with an assignee
    assignees:
      - jorana
