name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@21.12b0
        with:
          options: "--check --verbose"
          src: "./core_actions"
