# Test package every time

name: Pytest

# Controls when the action will run.

# Trigger this code when a new release is published
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - master

jobs:
  test_package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
      - name: Setup python
        uses: actions/setup-python@v2 # https://github.com/marketplace/actions/setup-miniconda
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python dependencies
        uses: py-actions/py-dependency-install@v3
      - name: Install dependencies
        run: |
          python setup.py test
      - name: goodbye
        run: echo goodbye
