name: Minimal cvmfs usage
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - name: Test CernVM-FS
      run: |
        source /cvmfs/xenon.opensciencegrid.org/releases/nT/development/setup.sh
        python -c "print('hello XENON!')"
        python -c "import strax; print(f'Strax {strax.__version__} from {strax}')"
